# Generated by Django 5.1.6 on 2025-03-31 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="probuct",
            name="is_sale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="probuct",
            name="sale_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="probuct",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
